[package]
name = "hj"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
config = "0.15.11"
xshell = "0.2.7"
duct = "1.0.0"
console = "0.16.0"
dialoguer = "0.11.0"
