name: Release

on:
  push:
    tags:
      - 'v*.*.*'  

env:
  PROJECT_NAME: hj  

permissions: read-all


jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux-x64
            target: x86_64-unknown-linux-gnu
            use-cross: true
            os: ubuntu-latest

          - name: linux-arm64
            target: aarch64-unknown-linux-gnu
            use-cross: true
            os: ubuntu-latest

          - name: windows-x64
            target: x86_64-pc-windows-gnu
            use-cross: true
            os: ubuntu-latest  # cross 也支持 windows targets

          # - name: windows-arm64
          #   target: aarch64-pc-windows-gnu
          #   use-cross: true
          #   os: ubuntu-latest

          - name: macos-x64
            target: x86_64-apple-darwin
            use-cross: false
            os: macos-latest

          - name: macos-arm64
            target: aarch64-apple-darwin
            use-cross: false
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cross (for Linux & Windows)
        if: matrix.use-cross == true
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        if: matrix.use-cross == true
        run: |
          mkdir -p dist
          BIN_SUFFIX=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            BIN_SUFFIX=".exe"
          fi
          cross build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/${PROJECT_NAME}${BIN_SUFFIX} \
            dist/${PROJECT_NAME}-${{ matrix.name }}${BIN_SUFFIX}

      - name: Build natively (for macOS only)
        if: matrix.use-cross == false
        shell: bash
        run: |
          mkdir -p dist
          BIN_SUFFIX=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            BIN_SUFFIX=".exe"
          fi
          cargo build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/${PROJECT_NAME}${BIN_SUFFIX} \
            dist/${PROJECT_NAME}-${{ matrix.name }}${BIN_SUFFIX}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release for version ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
